version: "3.9"
services:
#  prometheus_server:
#    container_name: "doubletapp-app-web"
#    image: ${IMAGE_NAME}
#    command: "python src/manage.py runprometheusserver"
#    build:
#      context: .
#    env_file:
#      - .env
#

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - 3060:3000